apiVersion: v1
kind: Service
metadata:
  name: surakshitha-ecr-service
  namespace: day17-surakshitha
spec:
  type: LoadBalancer
  selector:
    app: surakshitha-ecr-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
